# version: "3"
# services:
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW-ANONYMOUS_LOGIN=yes
#   kafka:
#     image: 'bitnami/kafka:2.8.0'
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhsot:9092
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_LOG_RETENTION_HOURS=6
#     depends_on:
#       - zookeeper

# version: "3"
# services:
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: 'bitnami/kafka:latest'
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://asgard03.moffatt.me:9092
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_LOG_RETENTION_HOURS=6
#     depends_on:
#       - zookeeper

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper